# permissions for end users to view mcservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mc-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcserver-viewer-role
rules:
- apiGroups:
  - servers.blamedevs.com
  resources:
  - mcservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servers.blamedevs.com
  resources:
  - mcservers/status
  verbs:
  - get
