---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - servers.blamedevs.com
  resources:
  - mcservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servers.blamedevs.com
  resources:
  - mcservers/finalizers
  verbs:
  - update
- apiGroups:
  - servers.blamedevs.com
  resources:
  - mcservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["tcproutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
